const AppActionTypes = {
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_FAILURE: "FETCH_FAILURE",
  FETCH_MENU_DISPLAY_SUCCESS: "FETCH_MENU_DISPLAY_SUCCESS",
  FETCH_CATEGORIES_SUCCESS: "FETCH_CATEGORIES_SUCCESS",
  CLEAR_API_RESULTS: "CLEAR_API_RESULTS",
};

export default AppActionTypes;
